language: python
python:
- '2.6'
- '2.7'
sudo: false
cache:
- apt
- pip
install:
- pip install -r requirements-dev.txt -e .
- pip install coverage coveralls Mako
services:
- redis-server
script: py.test --cov flask_bitmapist --cov-report term-missing --pep8 --flakes
after_success:
- coveralls
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: Tok8grsXdoAXuWhig0fO66CLW4SvQsSaRZJ0ZZ/2bkt276LrggcgdNYwSJs4qDuMYz1/eMFASLe0obfgd0EKtliHIZFQLW05aoLKABj6N0k0XhIrqkWWhwhYdL+P8rnsr2VPNEFcX+iXY9V93KBnCBnrixH+J6VaMBr/gvHEZuZbM+gWWDeN/C1P+4T/NtmsvQmSt1jv3pskn7MKpbikIwDNyTvvH1jVPu1mZuaZ0DP2WMO8Pqr1fXsQ3IWlNVULx/JK9wwYRDcCK41qKIjYxUXMYUTkPdxn4aBtJ/oiSNasLwB06x9PYTkbgVoXouj6yxRqJduSR/qCZ/jfaYGAWOhtPVbK3dbUv/qi6gy0Fa62Qd6uFVykUinNPTWz+uNfpmwyO8ZNSKAuyVRMQGJgY9jSXpWaVFQjZVrjyPjfGwo51sqvUYgL3rA8Zq70T4m/Nwb/f7hxHCWZkW0dNopuT3sviBuRBsvdyKvqh51CqKGWI9qV3nxltXjZ9v8GClXXs5PL/spvbmUwa91vgqUSLrK+RttETGxAjoak11A9/SLpXmJcBNBUVMG2xCGUlFR01njyUnPkgSWJI+8oKG1jWER0CvBMDHC8ydToE4sh6I8VPeX1s+G7wpHB9UBmWzOU05SMxrtlzWnDD+NzJTag8/HXN5FIs7DpNoSxTei/lVs=
