language: python

python:
  - "2.6"
  - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -e .
  - pip install coverage coveralls Mako

services:
  - redis-server

script: python setup.py test

branches:
  only:
    - master

# notifications:
#   slack:
#     on_success: always
#     on_failure: change