language: python

python:
  - "2.6"
  - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements-dev.txt -e .
  - pip install coverage coveralls Mako

services:
  - redis-server

script: py.test --cov flask_bitmapist --cov-report term-missing --pep8 --flakes

after_success:
  - coveralls

branches:
  only:
    - master

# notifications:
#   slack:
#     on_success: always
#     on_failure: change